on:
  schedule:
  - cron: '16 11 * * *'
  push:

name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: shovel-org/GithubActions@main
      env:
        GITH_EMAIL: lacvtg.a1.2023@gmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
        SCOOP_BRANCH: main
