on:
  schedule:
  - cron: '*/20 4 * * *'
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
    -
      uses: actions/checkout@v3
    -
      name: Checkout Scoop
      shell: pwsh
      run: |
        $env:SCOOP = Join-Path $env:USERPROFILE 'SCOOP'
        $env:SCOOP_HOME = Join-Path $env:SCOOP 'apps\scoop\current'
        [System.Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
        [System.Environment]::SetEnvironmentVariable('SCOOP_HOME', $env:SCOOP_HOME, 'User')
        Write-Output "SCOOP=$env:SCOOP" >> $env:GITHUB_ENV
        Write-Output "SCOOP_HOME=$env:SCOOP_HOME" >> $env:GITHUB_ENV
        Write-Output "$(Join-Path $env:SCOOP 'shims')" >> $env:GITHUB_PATH

        $f = Join-Path $env:USERPROFILE 'install.ps1'
        curl -L https://get.scoop.sh -o $f
        & $f -RunAsAdmin
    -
      name: Configure Git
      shell: pwsh
      run: |
        scoop install hub
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions
    -
      name: Excavator
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ~\scoop\apps\scoop\current\bin\auto-pr.ps1 -Upstream "$env:GITHUB_REPOSITORY`:main" -OriginBranch main -Dir bucket -Push -SkipUpdated
        ~\scoop\apps\scoop\current\bin\auto-pr.ps1 -Upstream "$env:GITHUB_REPOSITORY`:main" -OriginBranch main -Dir experimental -Push -SkipUpdated
