name: Excavator
on:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Sanity check
      run: echo $env:GITHUB_EVENT_NAME
    - name: Excavator
      uses: shovel-org/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITH_EMAIL: github-actions[bot]@users.noreply.github.com
        SKIP_UPDATED: '1'
